### ISSUE TITLE
[Suggestion] disable a superpower in some game modes

### ISSUE THREAD

**Issue by liquidman228** [Xemorr/superheroes#43]
Hey
It would be nice if it was possible to limit the use of superpowers in some modes, for example in the spectator
Because on my bedwars server people are abusing the creeper's power while in spectator mode

I have a lot of ideas for the plugin, by the way, and I'm thinking about getting a paid version, since it's become one of the server's main features. I can suggest a lot of ideas if you're interested

Thanks for the great plugin :)

**Comment by Xemorr** [comment]
In spectator, all powers are disabled and have been for many many many many versions. How is your spectator mode implemented?!
________________________________
From: liquidman228 ***@***.***>
Sent: 14 April 2023 19:35
To: Xemorr/superheroes ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Xemorr/superheroes] [Suggestion] disable a superpower in some game modes (Issue #43)


Hey
It would be nice if it was possible to limit the use of superpowers in some modes, for example in the spectator
Because on my bedwars server people are abusing the creeper's power while in spectator mode

I have a lot of ideas for the plugin, by the way, and I'm thinking about getting a paid version, since it's become one of the server's main features. I can suggest a lot of ideas if you're interested

Thanks for the great plugin :)

**Comment by liquidman228** [comment]
Oh, yeah, i've been not updated for a while. Im on 3.6.1
Didn't expect that it was fixed, because there is no such option in the config. Sorry

**Comment by Xemorr** [comment]
It should be in 3.6.1 as well. If you're in /gmsp, you have no hero from the perspective of the plugin.
________________________________

**Comment by liquidman228** [comment]
Its okay :)
Yeah, sure. Will join the server later
